### PR TITLE
Assignment 1, 2, 4

### PR DESCRIPTION
**Pull request by jyotijauhari**
Remaining assignment I will submit as soon as possible. 
Please let me know if any changes required.

### CODE REVIEW

**Comment by pr4nshul** [comment]
It's fine, although next time make a branch. It's just a good practice, rather than committing on master. Refer a video on youtube if needed.

**Comment by jyotijauhari** [comment]
> It's fine, although next time make a branch. It's just a good practice, rather than committing on master. Refer a video on youtube if needed.

New branch in the forked repo, right?

**Comment by pr4nshul** [comment]
yes

**Comment by jyotijauhari** [comment]
Ya sure! will take care from next time.

**Pull request merged**
